### PR TITLE
Adapting to new SpamCheck API

### PR DESCRIPTION
**Pull request by Yoric**

### CODE REVIEW

**Comment by richvdh** [comment]
which new spamcheck api?

**Comment by Yoric** [comment]
> which new spamcheck api?

The one in which we call `api.register_spam_checker_callbacks`. I don't know any better name than "new".

**Comment by richvdh** [comment]
oh right, sorry, yes, that makes sense.

**Comment by richvdh** [comment]
obviously the config will need to be updated when this is deployed, to avoid the hook being registered twice. You might want to consider a major version bump to reflect that?

**Comment by richvdh** [comment]
also the README will need an update: https://github.com/matrix-org/synapse-spamcheck-badlist#installation is no longer correct.

**Comment by Yoric** [comment]
> obviously the config will need to be updated when this is deployed, to avoid the hook being registered twice. You might want to consider a major version bump to reflect that?

Feels like I missed something. What needs to be changed in the config?

**Comment by richvdh** [comment]
> Feels like I missed something. What needs to be changed in the config?

The config needs to move to the separate `modules` section: https://matrix-org.github.io/synapse/develop/modules.html#using-modules.

@babolivier: is there a way for a module implementation to support both the new and the old config mechanism, so that config and code don't need to be updated at the same time? Presumably if the module implements two classes, one for each mechanism?

**Comment by babolivier** [comment]
> @babolivier: is there a way for a module implementation to support both the new and the old config mechanism, so that config and code don't need to be updated at the same time? Presumably if the module implements two classes, one for each mechanism?

That, or having the module's class both registering its callbacks against the new system and keeping their names so the legacy wrapper will pick them up - this is only doable for the spamchecker and the presence router afaict since the signatures of the callbacks with the legacy interface match those expected in the new one.

**Comment by richvdh** [comment]
> That, or having the module's class both registering its callbacks against the new system and keeping their names so the legacy wrapper will pick them up

that will mean that the hooks get registered twice, though?

**Comment by richvdh** [comment]
(it would be great to add this info to the porting doc)

**Pull request merged**
